version: '3.9'

services:
  mysql:
    build: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    volumes:
      - mydb:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  backend:
    build: backend
    container_name: backend
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      PORT: ${PORT}

volumes:
  mydb:
